/**
 * QuantMesh x402 Gateway Configuration
 * Defines network identifiers, USDC ASA IDs, receiver wallet addresses, and worker payout routing.
 * Follows the Algorand x402 AVM reference template specification.
 */

export const ALGORAND_TESTNET_CAIP2 = 'algorand:SGO1GKSzyE7IEPItTxCByw9x8FmnrCDexi9/cOUJOiI=';
export const USDC_TESTNET_ASA_ID = 10458941;

export const ROUTER_ADDRESS = process.env.ROUTER_ADDRESS || '4DTSNS35EP24IFWIGXSG5NSD3GDDTPHNVGEXSHG67JDEHUHUNFR3KJGPO4';

export const WORKER_PAYOUT_ADDRESSES = {
  A: process.env.WORKER_A_PAYOUT_ADDRESS || process.env.WORKER_A_PAYOUT_ADDR || '3VX4MDC3ZRJWCJIYRACWDZLKMP5OOI7UTDUDFYSJO2ESCIYDRFVQFEY55U',
  B: process.env.WORKER_B_PAYOUT_ADDRESS || process.env.WORKER_B_PAYOUT_ADDR || '4PIEYCWYYCPUIFNCLPP4BQ37PVFA23EF3GBYIK7VWE3QWZARC5RRTEVEIE',
  C: process.env.WORKER_C_PAYOUT_ADDRESS || process.env.WORKER_C_PAYOUT_ADDR || 'U55BSD7ZWOIP4ZSLAYU4MX344DJBPONX4YWI3PFWPVMV34TELFBZYG3E6E',
  D: process.env.WORKER_D_PAYOUT_ADDRESS || process.env.WORKER_D_PAYOUT_ADDR || 'B47KV6MF637THQAU6B6VM4JEQTKYFTJBUIYKCZPQ4E2QD6K67RV4XV5C6U',
  E: process.env.WORKER_E_PAYOUT_ADDRESS || process.env.WORKER_E_PAYOUT_ADDR || 'L6IQF5STONDUOKY2KRVOKWBTX5J54NSAAVG5NVLZCBULHAV6BWBTHN4PBI',
  F: process.env.WORKER_F_PAYOUT_ADDRESS || process.env.WORKER_F_PAYOUT_ADDR || 'DMJVKVBOPIBF6ZAEPNS3436GQPXRW2UYLIII4OO3LT5EMPNHQI7NMKOIKU',
  G: process.env.WORKER_G_PAYOUT_ADDRESS || process.env.WORKER_G_PAYOUT_ADDR || 'YM2IJR3Y3VMVDPWI4QBHHKJCYY6PPT6MC2T7U2E33AG5S3MLZW7TCQUNFI',
  H: process.env.WORKER_H_PAYOUT_ADDRESS || process.env.WORKER_H_PAYOUT_ADDR || 'J4LORKU4BKXQDQTFBZABYPU6LWLJUC4TQVDEHROK6OHNRGE4VC23K7JEFI',
};

export const FACILITATOR_URL = process.env.FACILITATOR_URL || 'https://facilitator.goplausible.xyz';
